[package]
name = "bingus-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
opt-level = 3

[dependencies]
anyhow = "1.0.75"
bingus-http = { path = "bingus-http" }
env_logger = "0.10.0"
log = "0.4.20"
proc-macro2 = "1.0.69"
quote = "1.0.33"
serde = "1.0.189"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
toml = "0.8.2"
