[package]
name = "bingus-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
opt-level = 3

[dependencies]
anyhow = "1.0.75"
bingus-http = { git = "https://gitlab.com/hyron-devs/bingus-http" }
colored = "2.0.4"
env_logger = "0.10.0"
humansize = "2.1.3"
log = "0.4.20"
mime = "0.3.17"
mime_guess = "2.0.4"
path-dedot = { version = "3.1.1", features = ["once_cell_cache"] }
proc-macro2 = "1.0.69"
quote = "1.0.33"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
toml = "0.8.2"
